import type { KlettersteigRoute } from "./types";

// ── Hohe Wand ─────────────────────────────────────────────────────────────────

export const HOHE_WAND_ROUTES: KlettersteigRoute[] = [
  {
    id: "hohe-wand-steirerspur",
    locationId: "hohe-wand",
    name: "Steirerspur",
    difficulty: "C/D",
    latitude: 47.8116,
    longitude: 16.0264,
    elevationGain: 280,
    description: "Klassiker, anspruchsvoll",
    parkingIds: ["hw-parkplatz-seiser-toni"],
  },
  {
    id: "hohe-wand-hanselsteig",
    locationId: "hohe-wand",
    name: "Hanselsteig",
    difficulty: "A/B",
    latitude: 47.8413,
    longitude: 16.0702,
    elevationGain: 200,
    description: "Einsteigerfreundlich",
    parkingIds: ["hw-parkplatz-stollhof"],
  },
  {
    id: "hohe-wand-wildenauersteig",
    locationId: "hohe-wand",
    name: "Wildenauersteig",
    difficulty: "C",
    latitude: 47.8105,
    longitude: 16.0207,
    elevationGain: 250,
    description: "Mittelschwer, schöne Aussicht",
    parkingIds: ["hw-parkplatz-seiser-toni"],
  },
  {
    id: "hohe-wand-gebirgsvereinssteig",
    locationId: "hohe-wand",
    name: "Gebirgsvereinssteig",
    difficulty: "B",
    latitude: 47.8093,
    longitude: 16.0199,
    elevationGain: 220,
    description: "Moderat",
    parkingIds: ["hw-parkplatz-seiser-toni"],
  },
  {
    id: "hohe-wand-guenther-schlesinger",
    locationId: "hohe-wand",
    name: "Günther-Schlesinger-Steig",
    difficulty: "B",
    latitude: 47.8110,
    longitude: 16.0220,
    elevationGain: 210,
    description: "Moderat, gut gesichert",
    parkingIds: ["hw-parkplatz-seiser-toni"],
  },
  {
    id: "hohe-wand-htl-steig",
    locationId: "hohe-wand",
    name: "HTL-Steig",
    difficulty: "B/C",
    latitude: 47.8279,
    longitude: 16.0504,
    elevationGain: 240,
    description: "Mittel bis schwer",
    parkingIds: ["hw-parkplatz-stollhof"],
  },
  {
    id: "hohe-wand-hubertussteig",
    locationId: "hohe-wand",
    name: "Hubertussteig",
    difficulty: "A",
    latitude: 47.8098,
    longitude: 16.0255,
    elevationGain: 180,
    description: "Leicht",
    parkingIds: ["hw-parkplatz-seiser-toni"],
  },
  {
    id: "hohe-wand-voellerin-steig",
    locationId: "hohe-wand",
    name: "Völlerin-Steig",
    difficulty: "C",
    latitude: 47.8281,
    longitude: 16.0474,
    elevationGain: 260,
    description: "Anspruchsvoll",
    parkingIds: ["hw-parkplatz-stollhof"],
  },
  {
    id: "hohe-wand-springlessteig",
    locationId: "hohe-wand",
    name: "Springlessteig",
    difficulty: "A/B",
    latitude: 47.8110,
    longitude: 16.0248,
    elevationGain: 190,
    description: "Einsteigerfreundlich",
    parkingIds: ["hw-parkplatz-seiser-toni"],
  },
];

// ── Rax ───────────────────────────────────────────────────────────────────────

export const RAX_ROUTES: KlettersteigRoute[] = [
  {
    id: "rax-haidsteig",
    locationId: "rax",
    name: "Haidsteig",
    difficulty: "C/D",
    latitude: 47.6978,
    longitude: 15.7342,
    elevationGain: 550,
    description: "Anspruchsvoll, alpiner Klassiker",
    parkingIds: ["rax-parkplatz-preiner-gscheid"],
  },
  {
    id: "rax-koenigsschusswandsteig",
    locationId: "rax",
    name: "Königsschusswandsteig",
    difficulty: "D/E",
    latitude: 47.7005,
    longitude: 15.7338,
    elevationGain: 380,
    description: "Sehr schwer, nur für Erfahrene",
    parkingIds: ["rax-parkplatz-preiner-gscheid"],
  },
  {
    id: "rax-preinerwandsteig",
    locationId: "rax",
    name: "Preinerwandsteig",
    difficulty: "A/B",
    latitude: 47.6984,
    longitude: 15.7397,
    elevationGain: 450,
    description: "Moderat, tolle Aussicht",
    parkingIds: ["rax-parkplatz-preiner-gscheid"],
  },
  {
    id: "rax-bismarcksteig",
    locationId: "rax",
    name: "Bismarcksteig",
    difficulty: "A",
    latitude: 47.6918,
    longitude: 15.7054,
    elevationGain: 400,
    description: "Leicht, ideal zum Einstieg",
    parkingIds: ["rax-parkplatz-preiner-gscheid"],
  },
  {
    id: "rax-wachthuettelkamm",
    locationId: "rax",
    name: "Wachthüttelkamm",
    difficulty: "B",
    latitude: 47.7463,
    longitude: 15.7642,
    elevationGain: 480,
    description: "Moderat, abwechslungsreich",
    parkingIds: ["rax-parkplatz-raxseilbahn"],
  },
  {
    id: "rax-gaislochsteig",
    locationId: "rax",
    name: "Gaislochsteig",
    difficulty: "A/B",
    latitude: 47.7261,
    longitude: 15.7497,
    elevationGain: 420,
    description: "Einsteigerfreundlich",
    parkingIds: ["rax-parkplatz-raxseilbahn"],
  },
  {
    id: "rax-rudolfsteig",
    locationId: "rax",
    name: "Rudolfsteig",
    difficulty: "B",
    latitude: 47.7319,
    longitude: 15.7578,
    elevationGain: 460,
    description: "Moderat, historischer Steig",
    parkingIds: ["rax-parkplatz-raxseilbahn"],
  },
];

// ── Schneeberg ────────────────────────────────────────────────────────────────

export const SCHNEEBERG_ROUTES: KlettersteigRoute[] = [
  {
    id: "schneeberg-av-steig",
    locationId: "schneeberg",
    name: "AV-Steig",
    difficulty: "B/C",
    latitude: 47.7292,
    longitude: 15.7550,
    elevationGain: 500,
    description: "Mittelschwer, alpin",
    parkingIds: ["sb-parkplatz-weichtalhaus"],
  },
  {
    id: "schneeberg-nandlgrat",
    locationId: "schneeberg",
    name: "Nandlgrat",
    difficulty: "C",
    latitude: 47.7809,
    longitude: 15.8254,
    elevationGain: 600,
    description: "Anspruchsvoll, exponiert",
    parkingIds: ["sb-parkplatz-losenheim"],
  },
  {
    id: "schneeberg-weichtalklamm",
    locationId: "schneeberg",
    name: "Weichtalklamm",
    difficulty: "A",
    latitude: 47.7486,
    longitude: 15.7691,
    elevationGain: 350,
    description: "Leicht, durch die Klamm",
    parkingIds: ["sb-parkplatz-weichtalhaus"],
  },
];

// ── Alle Routen ───────────────────────────────────────────────────────────────

export const ALL_KLETTERSTEIG_ROUTES: KlettersteigRoute[] = [
  ...HOHE_WAND_ROUTES,
  ...RAX_ROUTES,
  ...SCHNEEBERG_ROUTES,
];
