import type { KlettersteigRoute } from "./types";

export const RAX_ROUTES: KlettersteigRoute[] = [
  {
    id: "rax-haidsteig",
    locationId: "rax",
    name: "Haidsteig",
    difficulty: "C/D",
    latitude: 47.6978,
    longitude: 15.7342,
    elevationGain: 350,
    description: "Klassiker an der Preiner Wand, sehr anspruchsvoll",
    parkingLatitude: 47.6836,
    parkingLongitude: 15.7412,
  },
  {
    id: "rax-koenigsschusswandsteig",
    locationId: "rax",
    name: "Königsschusswandsteig",
    difficulty: "D/E",
    latitude: 47.7005,
    longitude: 15.7338,
    elevationGain: 400,
    description: "Extrem schwer, Preiner Wand",
    parkingLatitude: 47.6836,
    parkingLongitude: 15.7412,
  },
  {
    id: "rax-preinerwandsteig",
    locationId: "rax",
    name: "Preinerwandsteig",
    difficulty: "A/B",
    latitude: 47.6984,
    longitude: 15.7397,
    elevationGain: 300,
    description: "Klassiker, Preiner Wand",
    parkingLatitude: 47.6836,
    parkingLongitude: 15.7412,
  },
  {
    id: "rax-bismarcksteig",
    locationId: "rax",
    name: "Bismarcksteig",
    difficulty: "A",
    latitude: 47.6918,
    longitude: 15.7054,
    elevationGain: 200,
    description: "Leicht, Querung am Predigtstuhl",
    parkingLatitude: 47.6759,
    parkingLongitude: 15.7235,
  },
  {
    id: "rax-wachthuettelkamm",
    locationId: "rax",
    name: "Wachthüttelkamm",
    difficulty: "B",
    latitude: 47.7463,
    longitude: 15.7642,
    elevationGain: 250,
    description: "Moderat, Großes Höllental",
    parkingLatitude: 47.7473,
    parkingLongitude: 15.7657,
  },
  {
    id: "rax-gaislochsteig",
    locationId: "rax",
    name: "Gaislochsteig",
    difficulty: "A/B",
    latitude: 47.7261,
    longitude: 15.7497,
    elevationGain: 350,
    description: "Übergang im Großen Höllental",
    parkingLatitude: 47.7473,
    parkingLongitude: 15.7657,
  },
  {
    id: "rax-rudolfsteig",
    locationId: "rax",
    name: "Rudolfsteig",
    difficulty: "B",
    latitude: 47.738,
    longitude: 15.748,
    elevationGain: 300,
    description: "Gesicherter Steig, Großes Höllental",
    parkingLatitude: 47.7473,
    parkingLongitude: 15.7657,
  },
];

export const HOHE_WAND_ROUTES: KlettersteigRoute[] = [
  {
    id: "hohe-wand-steirerspur",
    locationId: "hohe-wand",
    name: "Steirerspur",
    difficulty: "C/D",
    latitude: 47.8295,
    longitude: 16.0385,
    elevationGain: 280,
    description: "Klassiker, anspruchsvoll",
    parkingLatitude: 47.8279,
    parkingLongitude: 16.0505,
  },
  {
    id: "hohe-wand-hanselsteig",
    locationId: "hohe-wand",
    name: "Hanselsteig",
    difficulty: "A/B",
    latitude: 47.828,
    longitude: 16.041,
    elevationGain: 200,
    description: "Einsteigerfreundlich",
    parkingLatitude: 47.8279,
    parkingLongitude: 16.0505,
  },
  {
    id: "hohe-wand-wildenauersteig",
    locationId: "hohe-wand",
    name: "Wildenauersteig",
    difficulty: "C",
    latitude: 47.8305,
    longitude: 16.036,
    elevationGain: 250,
    description: "Mittelschwer, schöne Aussicht",
    parkingLatitude: 47.8279,
    parkingLongitude: 16.0505,
  },
  {
    id: "hohe-wand-gebirgsvereinssteig",
    locationId: "hohe-wand",
    name: "Gebirgsvereinssteig",
    difficulty: "B",
    latitude: 47.827,
    longitude: 16.0395,
    elevationGain: 220,
    description: "Moderat",
    parkingLatitude: 47.8279,
    parkingLongitude: 16.0505,
  },
  {
    id: "hohe-wand-guenther-schlesinger",
    locationId: "hohe-wand",
    name: "Günther-Schlesinger-Steig",
    difficulty: "B",
    latitude: 47.8285,
    longitude: 16.037,
    elevationGain: 210,
    description: "Moderat, gut gesichert",
    parkingLatitude: 47.8279,
    parkingLongitude: 16.0505,
  },
  {
    id: "hohe-wand-htl-steig",
    locationId: "hohe-wand",
    name: "HTL-Steig",
    difficulty: "B/C",
    latitude: 47.831,
    longitude: 16.04,
    elevationGain: 240,
    description: "Mittel bis schwer",
    parkingLatitude: 47.8279,
    parkingLongitude: 16.0505,
  },
  {
    id: "hohe-wand-hubertussteig",
    locationId: "hohe-wand",
    name: "Hubertussteig",
    difficulty: "A",
    latitude: 47.826,
    longitude: 16.042,
    elevationGain: 180,
    description: "Leicht",
    parkingLatitude: 47.8279,
    parkingLongitude: 16.0505,
  },
  {
    id: "hohe-wand-voellerin-steig",
    locationId: "hohe-wand",
    name: "Völlerin-Steig",
    difficulty: "C",
    latitude: 47.83,
    longitude: 16.0345,
    elevationGain: 260,
    description: "Anspruchsvoll",
    parkingLatitude: 47.8279,
    parkingLongitude: 16.0505,
  },
  {
    id: "hohe-wand-springlessteig",
    locationId: "hohe-wand",
    name: "Springlessteig",
    difficulty: "A/B",
    latitude: 47.8275,
    longitude: 16.043,
    elevationGain: 190,
    description: "Einsteigerfreundlich",
    parkingLatitude: 47.8279,
    parkingLongitude: 16.0505,
  },
];
