import type { KlettersteigRoute } from "./types";

export const HOHE_WAND_ROUTES: KlettersteigRoute[] = [
  {
    id: "hohe-wand-steirerspur",
    locationId: "hohe-wand",
    name: "Steirerspur",
    difficulty: "C/D",
    latitude: 47.8295,
    longitude: 16.0385,
    elevationGain: 280,
    description: "Klassiker, anspruchsvoll",
  },
  {
    id: "hohe-wand-hanselsteig",
    locationId: "hohe-wand",
    name: "Hanselsteig",
    difficulty: "A/B",
    latitude: 47.828,
    longitude: 16.041,
    elevationGain: 200,
    description: "Einsteigerfreundlich",
  },
  {
    id: "hohe-wand-wildenauersteig",
    locationId: "hohe-wand",
    name: "Wildenauersteig",
    difficulty: "C",
    latitude: 47.8305,
    longitude: 16.036,
    elevationGain: 250,
    description: "Mittelschwer, schöne Aussicht",
  },
  {
    id: "hohe-wand-gebirgsvereinssteig",
    locationId: "hohe-wand",
    name: "Gebirgsvereinssteig",
    difficulty: "B",
    latitude: 47.827,
    longitude: 16.0395,
    elevationGain: 220,
    description: "Moderat",
  },
  {
    id: "hohe-wand-guenther-schlesinger",
    locationId: "hohe-wand",
    name: "Günther-Schlesinger-Steig",
    difficulty: "B",
    latitude: 47.8285,
    longitude: 16.037,
    elevationGain: 210,
    description: "Moderat, gut gesichert",
  },
  {
    id: "hohe-wand-htl-steig",
    locationId: "hohe-wand",
    name: "HTL-Steig",
    difficulty: "B/C",
    latitude: 47.831,
    longitude: 16.04,
    elevationGain: 240,
    description: "Mittel bis schwer",
  },
  {
    id: "hohe-wand-hubertussteig",
    locationId: "hohe-wand",
    name: "Hubertussteig",
    difficulty: "A",
    latitude: 47.826,
    longitude: 16.042,
    elevationGain: 180,
    description: "Leicht",
  },
  {
    id: "hohe-wand-voellerin-steig",
    locationId: "hohe-wand",
    name: "Völlerin-Steig",
    difficulty: "C",
    latitude: 47.83,
    longitude: 16.0345,
    elevationGain: 260,
    description: "Anspruchsvoll",
  },
  {
    id: "hohe-wand-springlessteig",
    locationId: "hohe-wand",
    name: "Springlessteig",
    difficulty: "A/B",
    latitude: 47.8275,
    longitude: 16.043,
    elevationGain: 190,
    description: "Einsteigerfreundlich",
  },
];
